"""``auditrum_makemigrations`` — generate Django migrations for audit triggers.

Walks the in-memory registry populated by ``@track``/``register()`` in each
app's ``audit.py`` module and diffs it against the trigger state the
existing migrations produce (see :mod:`auditrum.integrations.django.autodetector`).
Only what changed is written, per app, into ``{app}/migrations/``:

* a spec that is new, edited (``fields`` / ``exclude`` / ``extra_meta`` /
  ``log_condition`` / ``audit_table``), or whose rendered trigger body
  changed after an auditrum upgrade → :class:`InstallTrigger`;
* a spec that disappeared (``@track`` removed, model deleted, trigger
  renamed) → :class:`UninstallTrigger`.

When nothing changed, no file is written. ``--check`` exits non-zero when
migrations are missing, for CI.
"""

from __future__ import annotations

import datetime as _dt
import os
import sys
from pathlib import Path
from typing import Any

from django.apps import apps
from django.core.management.base import BaseCommand, CommandParser
from django.db.migrations.loader import MigrationLoader
from django.db.migrations.operations.base import Operation

from auditrum.integrations.django.autodetector import ChangeKind, TriggerChange, detect_changes
from auditrum.integrations.django.operations import (
    InstallTrigger,
    UninstallTrigger,
    _spec_to_deconstruct_kwargs,
)

_HEADER = """\
# Auto-generated by auditrum_makemigrations. Review and edit carefully.
from django.db import migrations

from auditrum.integrations.django.operations import {imports}
"""


def _change_to_operation(change: TriggerChange) -> Operation:
    kwargs = _spec_to_deconstruct_kwargs(change.spec)
    if change.kind is ChangeKind.UNINSTALL:
        return UninstallTrigger(**kwargs)
    return InstallTrigger(**kwargs, checksum=change.spec.build().checksum)


def _operation_repr(op: Operation) -> str:
    name, _, kwargs = op.deconstruct()
    joined = ",\n            ".join(f"{k}={v!r}" for k, v in kwargs.items())
    return f"{name}(\n            {joined},\n        )"


def _latest_migration_for_app(app_label: str) -> str | None:
    loader = MigrationLoader(None, ignore_no_migrations=True)
    leaves = loader.graph.leaf_nodes(app_label)
    if not leaves:
        return None
    return leaves[-1][1]


def _next_migration_name(app_label: str, suffix: str) -> str:
    loader = MigrationLoader(None, ignore_no_migrations=True)
    leaves = loader.graph.leaf_nodes(app_label)
    if not leaves:
        return f"0001_{suffix}"
    last = leaves[-1][1]
    try:
        num = int(last.split("_", 1)[0])
    except ValueError:
        num = 1
    return f"{num + 1:04d}_{suffix}"


def _render_migration(dependencies: list[tuple[str, str]], operations: list[Operation]) -> str:
    imports = ", ".join(sorted({type(op).__name__ for op in operations}))
    deps_repr = ",\n        ".join(repr(d) for d in dependencies)
    ops_repr = ",\n        ".join(_operation_repr(op) for op in operations)
    return (
        _HEADER.format(imports=imports)
        + "\n\n"
        + "class Migration(migrations.Migration):\n"
        + "    dependencies = [\n"
        + f"        {deps_repr},\n"
        + "    ]\n\n"
        + "    operations = [\n"
        + f"        {ops_repr},\n"
        + "    ]\n"
    )


def _describe(change: TriggerChange) -> str:
    sign = {ChangeKind.INSTALL: "+", ChangeKind.UPDATE: "~", ChangeKind.UNINSTALL: "-"}[change.kind]
    return f"    {sign} {change.kind.value} {change.trigger_name} on {change.spec.table} ({change.reason})"


class Command(BaseCommand):
    help = (
        "Generate Django migration files with InstallTrigger / UninstallTrigger "
        "operations for audit triggers whose @track / register() spec changed "
        "since the last migration."
    )
    # Like Django's makemigrations: auditrum.W001 would only repeat what
    # this command is about to fix.
    requires_system_checks = ()

    def add_arguments(self, parser: CommandParser) -> None:
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print the generated migration content instead of writing files.",
        )
        parser.add_argument(
            "--check",
            action="store_true",
            help="Exit with a non-zero status if trigger migrations are missing; write nothing.",
        )
        parser.add_argument(
            "--name",
            type=str,
            default=None,
            help="Override the migration name suffix (default: auditrum_<timestamp>).",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        changes = detect_changes()
        if not changes:
            self.stdout.write("No audit trigger changes detected.")
            return

        suffix = options.get("name") or ("auditrum_" + _dt.datetime.now().strftime("%Y%m%d_%H%M"))

        for app_label, app_changes in sorted(changes.items()):
            name = _next_migration_name(app_label, suffix)
            self.stdout.write(self.style.MIGRATE_HEADING(f"{app_label}/migrations/{name}.py"))
            for change in app_changes:
                self.stdout.write(_describe(change))

            if options["check"]:
                continue

            # Depend on our auditrum_django initial migration (context/auditlog schema)
            dependencies: list[tuple[str, str]] = [("auditrum_django", "0001_initial")]
            latest = _latest_migration_for_app(app_label)
            if latest is not None:
                dependencies.append((app_label, latest))
            content = _render_migration(
                dependencies, [_change_to_operation(c) for c in app_changes]
            )

            if options["dry_run"]:
                self.stdout.write(content)
                continue

            app_config = apps.get_app_config(app_label)
            migrations_dir = Path(app_config.path) / "migrations"
            if not migrations_dir.exists():
                migrations_dir.mkdir(parents=True, exist_ok=True)
                (migrations_dir / "__init__.py").write_text("", encoding="utf-8")
            out_path = migrations_dir / f"{name}.py"
            out_path.write_text(content, encoding="utf-8")
            self.stdout.write(self.style.SUCCESS(f"Wrote {os.path.relpath(out_path)}"))

        if options["check"]:
            sys.exit(1)
