"""``auditrum_makemigrations`` — generate Django migrations for audit triggers.

Walks the in-memory registry populated by ``@track``/``register()`` in each
app's ``audit.py`` module, groups the specs by the app label of their
tracked model, and writes a migration file with :class:`InstallTrigger`
operations into ``{app}/migrations/``.

Unlike Django's ``makemigrations``, this command does not diff against
prior migrations — it always writes a snapshot of the current registry
state. Reviewing the generated file in git + running ``migrate`` is the
single source of truth for what's applied.
"""

from __future__ import annotations

import datetime as _dt
import os
from pathlib import Path
from typing import Any

from django.apps import apps
from django.core.management.base import BaseCommand
from django.db.migrations.loader import MigrationLoader

from auditrum.integrations.django.tracking import specs_by_app_label
from auditrum.tracking import TrackSpec

_HEADER = '''\
# Auto-generated by auditrum_makemigrations. Review and edit carefully.
from django.db import migrations

from auditrum.integrations.django.operations import InstallTrigger
'''


def _spec_to_operation_repr(spec: TrackSpec) -> str:
    parts = [f"table={spec.table!r}"]
    if spec.audit_table != "auditlog":
        parts.append(f"audit_table={spec.audit_table!r}")
    if spec.fields.kind != "all":
        parts.append(f"fields_kind={spec.fields.kind!r}")
        parts.append(f"fields={list(spec.fields.fields)!r}")
    if spec.extra_meta_fields:
        parts.append(f"extra_meta_fields={list(spec.extra_meta_fields)!r}")
    if spec.log_condition is not None:
        parts.append(f"log_condition={spec.log_condition!r}")
    if spec.trigger_name is not None:
        parts.append(f"trigger_name={spec.trigger_name!r}")
    joined = ",\n            ".join(parts)
    return f"InstallTrigger(\n            {joined},\n        )"


def _latest_migration_for_app(app_label: str) -> str | None:
    loader = MigrationLoader(None, ignore_no_migrations=True)
    leaves = loader.graph.leaf_nodes(app_label)
    if not leaves:
        return None
    return leaves[-1][1]


def _next_migration_name(app_label: str, suffix: str) -> str:
    loader = MigrationLoader(None, ignore_no_migrations=True)
    leaves = loader.graph.leaf_nodes(app_label)
    if not leaves:
        return f"0001_{suffix}"
    last = leaves[-1][1]
    try:
        num = int(last.split("_", 1)[0])
    except ValueError:
        num = 1
    return f"{num + 1:04d}_{suffix}"


def _render_migration(
    app_label: str, dependencies: list[tuple[str, str]], specs: list[TrackSpec]
) -> str:
    deps_repr = ",\n        ".join(repr(d) for d in dependencies)
    ops_repr = ",\n        ".join(_spec_to_operation_repr(s) for s in specs)
    return (
        _HEADER
        + "\n\n"
        + "class Migration(migrations.Migration):\n"
        + "    dependencies = [\n"
        + f"        {deps_repr},\n"
        + "    ]\n\n"
        + "    operations = [\n"
        + f"        {ops_repr},\n"
        + "    ]\n"
    )


class Command(BaseCommand):
    help = (
        "Generate Django migration files with InstallTrigger operations for "
        "all models registered via auditrum @track or register()."
    )

    def add_arguments(self, parser: Any) -> None:
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print the generated migration content instead of writing files.",
        )
        parser.add_argument(
            "--name",
            type=str,
            default=None,
            help="Override the migration name suffix (default: auditrum_<timestamp>).",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        grouped = specs_by_app_label()
        if not grouped:
            self.stdout.write(self.style.WARNING("No @track-decorated models found."))
            return

        suffix = options.get("name") or (
            "auditrum_" + _dt.datetime.now().strftime("%Y%m%d_%H%M")
        )

        for app_label, items in grouped.items():
            specs = [spec for _, spec in items]
            dependencies: list[tuple[str, str]] = []
            # Depend on our auditrum_django initial migration (context/auditlog schema)
            dependencies.append(("auditrum_django", "0001_initial"))
            latest = _latest_migration_for_app(app_label)
            if latest is not None:
                dependencies.append((app_label, latest))

            name = _next_migration_name(app_label, suffix)
            content = _render_migration(app_label, dependencies, specs)

            if options["dry_run"]:
                self.stdout.write(self.style.NOTICE(f"--- {app_label}/migrations/{name}.py"))
                self.stdout.write(content)
                continue

            app_config = apps.get_app_config(app_label)
            migrations_dir = Path(app_config.path) / "migrations"
            if not migrations_dir.exists():
                migrations_dir.mkdir(parents=True, exist_ok=True)
                (migrations_dir / "__init__.py").write_text("", encoding="utf-8")
            out_path = migrations_dir / f"{name}.py"
            out_path.write_text(content, encoding="utf-8")
            self.stdout.write(
                self.style.SUCCESS(f"Wrote {os.path.relpath(out_path)}")
            )
